// function Persona(nombrePila, apellido, edad, genero, jugar, bailar) {
//     this.nombre = {
//       nombrePila,
//       apellido
//     };
//     this.edad = edad;
//     this.genero = genero;
//     this.intereses = {
//         jugar, 
//         bailar
//     };
//   };

// //   var nombrePila = "Aquiles"
// //   var apellido = "Gutierrez"
// //   var edad = 40
// //   var genero = "masculino"
// //   var intereses = "aprender js"


//   Persona.prototype.saludo = function() {
//     return '¡Hola! soy ' + this.nombre.nombrePila + ' ' + this.nombre.apellido + ',' + " tengo " + this.edad + " años." + " mi género es " + this.genero + " me gusta jugar " + this.intereses.jugar + " y bailar " + this.intereses.bailar;
//   };

//   let nuevaPersona = new Persona("Aquiles", "Gutiérrez", 40, "masculino", "fútbol", "salsa");
// //   var nuevaPersona2 = new Persona("Sutanito", "Perez", 38, "masculino", "aprender js" );
//   console.log(nuevaPersona.saludo());   
// //   console.log(nuevaPersona2.saludo());